Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/05/2022
Var
   N1, N2, M: real


Inicio
      Escreva("Digite um numero: ")
      Leia(N1)
      Escreva("Digite outro numero: ")
      Leia(N2)
      M <- (N1 + N2) / 2
      EscrevaL("A media será ", M)


Fimalgoritmo